services:
  web:
    container_name: apache_damien
    image: httpd:latest
    ports:
      - "80:80"

  database:
    container_name: mariadb_damien
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: test
    volumes: 
      - mariadb_data:/var/lib/mysql

volumes: 
  mariadb_data:
